# -*- coding: utf-8 -*-
"""pyhtonJul25Class

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GG9U-XSUNpV2QkNYJ1_5hy-7oD_EkXDe
"""

from datetime import datetime
odd_number = list(range(1, 60, 2))
current_time = datetime.today().minute
if current_time in odd_number:
    print("This is an odd number") 
else:
    print("This is an even number")

datetime.today().day

datetime.today().year

students = ['alice', 'david', 'Rakesh', 'Jose', 'Vani'] 

print("Here are the first three students in my class:")
for student in students[0:3]:
    print(student.title())

alien_0 = {'color': 'green', 'points': 5}
print(alien_0['color'])
print(alien_0['points'])

sizes = ('large' , 'Small' , 'medium')
print(sizes[0])  
print(sizes[-1])

def vacation(destination):
    """Display a simple greeting."""
    print("For my next vacation I am planning a trip to  " + destination.title() + "!")
    
vacation('alaska')

def realname(first_name, last_name, middle_name=''):
    """Return a full name."""
    if middle_name:
        full_name = first_name + ' ' +  middle_name + ' ' + last_name
    else:
        full_name = first_name + ' ' + last_name
    return full_name.title()
realname("anuroop","nag")

